/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AITool = IDL.Record({
  'id' : IDL.Nat,
  'url' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'category' : IDL.Text,
});

export const idlService = IDL.Service({
  'addTool' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [IDL.Record({ 'id' : IDL.Nat })],
      [],
    ),
  'deleteTool' : IDL.Func([IDL.Nat], [], []),
  'getAllTools' : IDL.Func([], [IDL.Vec(AITool)], ['query']),
  'getFeaturedTools' : IDL.Func([], [IDL.Vec(AITool)], ['query']),
  'getToolById' : IDL.Func([IDL.Nat], [IDL.Opt(AITool)], ['query']),
  'getToolsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(AITool)], ['query']),
  'searchTools' : IDL.Func([IDL.Text], [IDL.Vec(AITool)], ['query']),
  'updateTool' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AITool = IDL.Record({
    'id' : IDL.Nat,
    'url' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'category' : IDL.Text,
  });
  
  return IDL.Service({
    'addTool' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [IDL.Record({ 'id' : IDL.Nat })],
        [],
      ),
    'deleteTool' : IDL.Func([IDL.Nat], [], []),
    'getAllTools' : IDL.Func([], [IDL.Vec(AITool)], ['query']),
    'getFeaturedTools' : IDL.Func([], [IDL.Vec(AITool)], ['query']),
    'getToolById' : IDL.Func([IDL.Nat], [IDL.Opt(AITool)], ['query']),
    'getToolsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(AITool)], ['query']),
    'searchTools' : IDL.Func([IDL.Text], [IDL.Vec(AITool)], ['query']),
    'updateTool' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };