/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AITool {
  'id' : bigint,
  'url' : string,
  'name' : string,
  'description' : string,
  'isFeatured' : boolean,
  'category' : string,
}
export interface _SERVICE {
  'addTool' : ActorMethod<
    [string, string, string, string, boolean],
    { 'id' : bigint }
  >,
  'deleteTool' : ActorMethod<[bigint], undefined>,
  'getAllTools' : ActorMethod<[], Array<AITool>>,
  'getFeaturedTools' : ActorMethod<[], Array<AITool>>,
  'getToolById' : ActorMethod<[bigint], [] | [AITool]>,
  'getToolsByCategory' : ActorMethod<[string], Array<AITool>>,
  'searchTools' : ActorMethod<[string], Array<AITool>>,
  'updateTool' : ActorMethod<
    [bigint, string, string, string, string, boolean],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];